-- Inspiration Soft Solutions contact form table
-- Run this in Supabase Dashboard > SQL Editor.

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  company text,
  service text,
  message text not null
);

alter table public.contact_messages enable row level security;

drop policy if exists "Allow public contact inserts" on public.contact_messages;
create policy "Allow public contact inserts"
on public.contact_messages
for insert
to anon
with check (
  length(trim(name)) > 0
  and length(trim(email)) > 0
  and length(trim(message)) > 0
);

-- Demo/admin-page read policy.
-- NOTE: this allows browser clients with the publishable key to read contact messages.
-- For production, replace this with Supabase Auth, an Edge Function, or your own backend.
drop policy if exists "Allow demo admin contact reads" on public.contact_messages;
create policy "Allow demo admin contact reads"
on public.contact_messages
for select
to anon
using (true);

-- Dynamic website content tables.
-- Edit these rows in Supabase to update the public website without changing code.

create table if not exists public.site_services (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_stats (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  value text not null,
  label text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_process_steps (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_contact_points (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.site_services enable row level security;
alter table public.site_products enable row level security;
alter table public.site_stats enable row level security;
alter table public.site_process_steps enable row level security;
alter table public.site_contact_points enable row level security;

drop policy if exists "Allow public service reads" on public.site_services;
create policy "Allow public service reads" on public.site_services
for select to anon using (is_active = true);

drop policy if exists "Allow public product reads" on public.site_products;
create policy "Allow public product reads" on public.site_products
for select to anon using (is_active = true);

drop policy if exists "Allow public stats reads" on public.site_stats;
create policy "Allow public stats reads" on public.site_stats
for select to anon using (is_active = true);

drop policy if exists "Allow public process step reads" on public.site_process_steps;
create policy "Allow public process step reads" on public.site_process_steps
for select to anon using (is_active = true);

drop policy if exists "Allow public contact point reads" on public.site_contact_points;
create policy "Allow public contact point reads" on public.site_contact_points
for select to anon using (is_active = true);

insert into public.site_services (slug, title, description, display_order) values
  ('custom-web-application', 'Custom Web Application', 'Secure portals, dashboards, workflow engines, CRMs, ERP modules, and business tools built around your exact process.', 1),
  ('website-design', 'Website Design', 'Professional, responsive interfaces with clear content, elegant motion, fast loading, and a brand-first visual system.', 2),
  ('logo-creation', 'Logo Creation', 'Distinct logo concepts, refinements, usage guidelines, and launch-ready brand assets for digital and print.', 3),
  ('software-development', 'Software Development', 'End-to-end software planning, UI, backend, integrations, testing, deployment, and long-term enhancements.', 4),
  ('website-development', 'Website Development', 'Corporate websites, product sites, CMS-enabled pages, landing pages, SEO structure, and performance-minded delivery.', 5),
  ('database-development', 'Database Development', 'Relational database design, reporting structures, migrations, optimization, backups, and secure access patterns.', 6),
  ('hosting-maintenance', 'Hosting & Maintenance', 'Managed deployment, uptime checks, domain/email coordination, SSL, updates, bug fixes, and release support.', 7)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  display_order = excluded.display_order,
  updated_at = now();

insert into public.site_products (slug, title, description, display_order) values
  ('inventory-management', 'Inventory Management', 'Stock tracking, purchase flow, barcode-ready item control, warehouse views, alerts, and inventory reports.', 1),
  ('construction-management-system', 'Construction Management System', 'Project planning, material tracking, contractor billing, site progress, approvals, documents, and cost visibility.', 2),
  ('account-opening-ekyc-module', 'Account Opening / eKYC Module', 'Digital onboarding for finance companies with customer capture, document upload, verification workflow, and audit history.', 3)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  display_order = excluded.display_order,
  updated_at = now();

insert into public.site_stats (slug, value, label, display_order) values
  ('uptime', '99.9%', 'hosting-ready uptime approach', 1),
  ('capabilities', '7+', 'digital service capabilities', 2),
  ('solution-families', '3', 'ready product solution families', 3),
  ('support', '24/7', 'maintenance mindset', 4)
on conflict (slug) do update set
  value = excluded.value,
  label = excluded.label,
  display_order = excluded.display_order,
  updated_at = now();

insert into public.site_process_steps (slug, title, display_order) values
  ('discovery', 'Discovery', 1),
  ('design', 'Design', 2),
  ('development', 'Development', 3),
  ('testing', 'Testing', 4),
  ('launch', 'Launch', 5),
  ('support', 'Support', 6)
on conflict (slug) do update set
  title = excluded.title,
  display_order = excluded.display_order,
  updated_at = now();

insert into public.site_contact_points (slug, label, display_order) values
  ('software-consultation', 'Custom software consultation', 1),
  ('product-demos', 'Product solution demos', 2),
  ('support-planning', 'Hosting and support planning', 3)
on conflict (slug) do update set
  label = excluded.label,
  display_order = excluded.display_order,
  updated_at = now();
